name: Deploy to Firebase Hosting and Functions on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout your code
      - uses: actions/checkout@v4

      # Install & build the frontend
      - name: Install and Build Frontend
        run: npm install && npm run build
        working-directory: ./frontend

      # Install dependencies for Firebase Functions
      - name: Install Functions Dependencies
        run: npm install
        working-directory: ./functions

      # Build Firebase Functions
      - name: Build Firebase Functions
        run: npm run build
        working-directory: ./functions
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HAPPYSCHOOL_99F85 }}
          channelId: live
          projectId: happyschool-99f85
