name: Deploy to Firebase

on:
  push:
    branches:
      - main # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASEAPIKEY: ${{ secrets.FIREBASEAPIKEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase using service account
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > "${HOME}/firebase-key.json"
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token "$(firebase auth:application-default login --cred ${HOME}/firebase-key.json)"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
